frr defaults traditional
hostname mls1-bgp-r1
!
ip route 192.168.1.0/24 Null0
!
router bgp 65001
 bgp router-id 10.1.12.2
 no bgp ebgp-requires-policy
 neighbor 10.1.12.3 remote-as 65002
 !
 address-family ipv4 unicast
  network 192.168.1.0/24
 exit-address-family
!
